### ISSUE TITLE
RuntimeError: CUDA out of memory in training

### ISSUE THREAD

**Issue by RonenHong** [OpenNMT/OpenNMT-py#1161]
Hi, I just followed as instructed from https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/FAQ.md 

but I encountered CUDA out of memory during training.
I'm using 1080Ti on ubuntu.

how can I resolve this?
I already tried reduce batch_size as 1024 but no luck.

For preprocessing:
python preprocess.py -train_src data/ko/train.txt -train_tgt data/en/train.txt -valid_src data/ko/valid.txt -valid_tgt data/en/valid.txt -save_data data/ko2en

For training:
python train.py -data data/ko2en -save_model ko2en -layers 6 -rnn_size 512 -word_vec_size 512 -transformer_ff 2048 -heads 8 -encoder_type transformer -decoder_type transformer -position_encoding -train_steps 200000 -max_generator_batches 2 -dropout 0.1 -batch_size 4096 -batch_type tokens -normalization tokens -accum_count 2 -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 2 -max_grad_norm 0 -param_init 0 -param_init_glorot -label_smoothing 0.1 -valid_steps 10000 -save_checkpoint_steps 10000 -world_size 1 -gpu_ranks 0

[2019-01-08 12:25:09,533 INFO] encoder: 24837120
[2019-01-08 12:25:09,533 INFO] decoder: 40997916
[2019-01-08 12:25:09,533 INFO] * number of parameters: 65835036
[2019-01-08 12:25:09,536 INFO] Starting training on GPU: [0]
[2019-01-08 12:25:09,536 INFO] Start training...
[2019-01-08 12:25:15,974 INFO] Loading dataset from data/ko2en.train.0.pt, number of examples: 442701
.
.
.
2019-01-08 13:56:28,677 INFO] Step 10000/200000; acc:  76.61; ppl:  2.58; xent: 0.95; lr: 0.00088; 8790/13085 tok/s;   5479 sec
[2019-01-08 13:56:32,355 INFO] Loading dataset from data/ko2en.valid.0.pt, number of examples: 154419
Traceback (most recent call last):
  File "train.py", line 120, in <module>
    main(opt)
  File "train.py", line 51, in main
    single_main(opt, 0)
  File "/home/kyungsoo/workspace/NLP/OpenNMT-py/onmt/train_single.py", line 154, in main
    trainer.train(train_iter, valid_iter, opt.train_steps, opt.valid_steps)
  File "/home/kyungsoo/workspace/NLP/OpenNMT-py/onmt/trainer.py", line 188, in train
    valid_stats = self.validate(valid_iter)
  File "/home/kyungsoo/workspace/NLP/OpenNMT-py/onmt/trainer.py", line 233, in validate
    outputs, attns = self.model(src, tgt, src_lengths)
  File "/home/kyungsoo/miniconda3/envs/opennmt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kyungsoo/workspace/NLP/OpenNMT-py/onmt/models/model.py", line 46, in forward
    memory_lengths=lengths)
  File "/home/kyungsoo/miniconda3/envs/opennmt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kyungsoo/workspace/NLP/OpenNMT-py/onmt/decoders/transformer.py", line 232, in forward
    step=step)
  File "/home/kyungsoo/miniconda3/envs/opennmt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kyungsoo/workspace/NLP/OpenNMT-py/onmt/decoders/transformer.py", line 92, in forward
    output = self.feed_forward(self.drop(mid) + query)
  File "/home/kyungsoo/miniconda3/envs/opennmt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kyungsoo/workspace/NLP/OpenNMT-py/onmt/modules/position_ffn.py", line 38, in forward
    inter = self.dropout_1(self.relu(self.w_1(self.layer_norm(x))))
  File "/home/kyungsoo/miniconda3/envs/opennmt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kyungsoo/miniconda3/envs/opennmt/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 67, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/kyungsoo/miniconda3/envs/opennmt/lib/python3.6/site-packages/torch/nn/functional.py", line 1354, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA out of memory. Tried to allocate 39.75 MiB (GPU 0; 10.91 GiB total capacity; 9.17 GiB already allocated; 35.88 MiB free; 865.22 MiB cached)

**Comment by vince62s** [comment]
are you on master ?
if so it should not happen with the default valid batch size of 16 (IIRC) but you can decrease it.

**Comment by RonenHong** [comment]
yes, I'm on master
reduced till 512 for size of batch, so far so good.

**Comment by vince62s** [comment]
You are mistaken.
you can keep the batch_size=4096
you need to reduce the validation batch size (default value is 32 or 16 ie sentences, not token)
flag is -valid_batch_size

**Comment by jennhu** [comment]
I have the same CUDA memory error. I tried reducing `-valid_batch_size` from default 32 to 16, 8, 4, 2, and 1, but that didn't help. 

To clarify, I am training on ~1M sentences and am using all the default parameters for `train.py`.

Here is the full error:

```
[2019-02-04 10:19:28,536 INFO]  * src vocab size = 794419
[2019-02-04 10:19:28,536 INFO]  * tgt vocab size = 794421
[2019-02-04 10:19:28,537 INFO] Building model...
[2019-02-04 10:20:05,836 INFO] NMTModel(
  (encoder): RNNEncoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(794419, 500, padding_idx=1)
        )
      )
    )
    (rnn): LSTM(500, 500, num_layers=2, dropout=0.3)
  )
  (decoder): InputFeedRNNDecoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(794421, 500, padding_idx=1)
        )
      )
    )
    (dropout): Dropout(p=0.3)
    (rnn): StackedLSTM(
      (dropout): Dropout(p=0.3)
      (layers): ModuleList(
        (0): LSTMCell(1000, 500)
        (1): LSTMCell(500, 500)
      )
    )
  )
  (generator): Sequential(
    (0): Linear(in_features=500, out_features=794421, bias=True)
    (1): LogSoftmax()
  )
)
[2019-02-04 10:20:05,837 INFO] encoder: 401217500
[2019-02-04 10:20:05,837 INFO] decoder: 800223421
[2019-02-04 10:20:05,837 INFO] * number of parameters: 1201440921
[2019-02-04 10:20:05,840 INFO] Starting training on GPU: [0, 1]
[2019-02-04 10:20:05,840 INFO] Start training...
[2019-02-04 10:20:19,492 INFO] Loading dataset from data/wiki/1M/leipzig/wiki.train.0.pt, number of examples: 499999
Traceback (most recent call last):
  File "train.py", line 120, in <module>
    main(opt)
  File "train.py", line 48, in main
    p.join()
  File "/om2/user/jennhu/conda/envs/neural-nlp/lib/python3.6/multiprocessing/process.py", line 124, in join
    res = self._popen.wait(timeout)
  File "/om2/user/jennhu/conda/envs/neural-nlp/lib/python3.6/multiprocessing/popen_fork.py", line 57, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/om2/user/jennhu/conda/envs/neural-nlp/lib/python3.6/multiprocessing/popen_fork.py", line 35, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "train.py", line 105, in signal_handler
    raise Exception(msg)
Exception:

-- Tracebacks above this line can probably
                 be ignored --

Traceback (most recent call last):
  File "/om/user/jennhu/OpenNMT-py/train.py", line 63, in run
    single_main(opt, device_id)
  File "/om/user/jennhu/OpenNMT-py/onmt/train_single.py", line 146, in main
    trainer.train(train_iter, valid_iter, opt.train_steps, opt.valid_steps)
  File "/om/user/jennhu/OpenNMT-py/onmt/trainer.py", line 173, in train
    report_stats)
  File "/om/user/jennhu/OpenNMT-py/onmt/trainer.py", line 279, in _gradient_accumulation
    loss.backward()
  File "/home/jennhu/.local/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/jennhu/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 2.84 GiB (GPU 0; 11.93 GiB total capacity; 10.22 GiB already allocated; 1.18 GiB free; 27.69 MiB cached)
```

Any advice on how to resolve this?

**Comment by RonenHong** [comment]
@jennhu as I said I reduced the batch size and after pull master branch to up to date, it also allowed me to have batch size 4096, so actually I didn't change it at all, I trained 196M file, so I guess train file size won't be an issue. your GPU might be occupied by others? check it with ``` nvidia-smi -l```

**Comment by jennhu** [comment]
Thanks @RonenHong. I monitored the memory and got 

```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     17806      C   ...jennhu/conda/envs/neural-nlp/bin/python  5078MiB |
|    1     17807      C   ...jennhu/conda/envs/neural-nlp/bin/python  5078MiB |
+-----------------------------------------------------------------------------+
Mon Feb 11 15:12:07 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.77                 Driver Version: 390.77                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  On   | 00000000:06:00.0 Off |                  N/A |
| 22%   54C    P2    86W / 250W |  12152MiB / 12212MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  On   | 00000000:81:00.0 Off |                  N/A |
| 22%   50C    P2    99W / 250W |  10868MiB / 12212MiB |     48%      Default |
+-------------------------------+----------------------+----------------------+
```
right before the job crashed. So it seems like the GPU isn't occupied by others.

Could this be related to [this PyTorch/CUDA issue](https://github.com/pytorch/pytorch/issues/15563)?

**Comment by vince62s** [comment]
your vocab sizes are way too high.don't use more than 50k.

**Comment by jennhu** [comment]
Isn't the default `src_vocab_size` and `tgt_vocab_size` 50k? I didn't pass any flags to `preprocess.py` that would change the vocab size.

**Comment by LeonCrashCode** [comment]
I face a similar CUDA OOM problem. 

`python ../../../../OpenNMT-py/train.py -data ../data-bin/data -src_word_vec_size 300 -tgt_word_vec_size 300 -layers 6 -rnn_size 300 -transformer_ff 2048 -heads 6 -save_model checkpoints/checkpoints -log_file log -dropout 0.2 -bridge -encoder_type transformer -decoder_type transformer -position_encoding -copy_attn -copy_attn_type dot -max_relative_positions 1000 -global_attention general -report_every 50 -train_steps 8000 -batch_size 8 -batch_type tokens -max_generator_batches 0 -optim adam -learning_rate 0.001 -learning_rate_decay 0.7 -max_grad_norm 0 -adam_beta2 0.998 -start_decay_steps 1000 -decay_steps 400 -pre_word_vecs_enc ../data-bin/embeddings-300.enc.pt -pre_word_vecs_dec ../data-bin/embeddings-300.dec.pt -save_checkpoint_steps 400 -valid_steps 400 -param_init 0 -param_init_glorot -normalization tokens -accum_count 2 -seed 1234567 -world_size 4 -gpu_ranks 0 1 2 3 `

The log shows
```
[2019-03-18 21:02:15,920 INFO]  * src vocab size = 14509
[2019-03-18 21:02:15,920 INFO]  * tgt vocab size = 14294
[2019-03-18 21:02:15,920 INFO] Building model...
[2019-03-18 21:02:19,961 INFO] NMTModel(
  (encoder): TransformerEncoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(14509, 300, padding_idx=1)
        )
        (pe): PositionalEncoding(
          (dropout): Dropout(p=0.2)
        )
      )
    )
    (transformer): ModuleList(
      (0): TransformerEncoderLayer(
        (self_attn): MultiHeadedAttention(
          (linear_keys): Linear(in_features=300, out_features=300, bias=True)
          (linear_values): Linear(in_features=300, out_features=300, bias=True)
          (linear_query): Linear(in_features=300, out_features=300, bias=True)
          (softmax): Softmax()
          (dropout): Dropout(p=0.2)
          (final_linear): Linear(in_features=300, out_features=300, bias=True)
          (relative_positions_embeddings): Embedding(2001, 50)
        )
        (feed_forward): PositionwiseFeedForward(
          (w_1): Linear(in_features=300, out_features=2048, bias=True)
          (w_2): Linear(in_features=2048, out_features=300, bias=True)
          (layer_norm): LayerNorm(torch.Size([300]), eps=1e-06, elementwise_affine=True)
          (dropout_1): Dropout(p=0.2)
.....

[2019-03-18 21:02:19,970 INFO] encoder: 14514888
[2019-03-18 21:02:19,970 INFO] decoder: 20923983
[2019-03-18 21:02:19,970 INFO] * number of parameters: 35438871
[2019-03-18 21:02:19,974 INFO] Starting training on GPU: [0, 1, 2, 3]
[2019-03-18 21:02:19,974 INFO] Start training loop and validate every 400 steps...
/disk/scratch/jiangming/workspace/DRTSparsing/lib64/python3.6/site-packages/torchtext/data/field.py:359: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach(
) or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  var = torch.tensor(arr, dtype=self.dtype, device=device)
/disk/scratch/jiangming/workspace/DRTSparsing/lib64/python3.6/site-packages/torchtext/data/field.py:359: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach(
) or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  var = torch.tensor(arr, dtype=self.dtype, device=device)
/disk/scratch/jiangming/workspace/DRTSparsing/lib64/python3.6/site-packages/torchtext/data/field.py:359: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach(
) or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  var = torch.tensor(arr, dtype=self.dtype, device=device)
[2019-03-18 21:02:24,214 INFO] Loading dataset from ../data-bin/data.train.0.pt, number of examples: 7945
/disk/scratch/jiangming/workspace/DRTSparsing/lib64/python3.6/site-packages/torchtext/data/field.py:359: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach(
) or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  var = torch.tensor(arr, dtype=self.dtype, device=device)
Traceback (most recent call last):
  File "../../../../OpenNMT-py/train.py", line 109, in <module>
    main(opt)
  File "../../../../OpenNMT-py/train.py", line 36, in main
    p.join()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/multiprocessing/process.py", line 124, in join
    res = self._popen.wait(timeout)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 51, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 29, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "../../../../OpenNMT-py/train.py", line 93, in signal_handler
    raise Exception(msg)
Exception: 

-- Tracebacks above this line can probably
                 be ignored --

Traceback (most recent call last):
  File "/disk/scratch/jiangming/workspace/DRTSparsing/OpenNMT-py/train.py", line 51, in run
    single_main(opt, device_id)
  File "/disk/scratch/jiangming/workspace/DRTSparsing/OpenNMT-py/onmt/train_single.py", line 116, in main
    valid_steps=opt.valid_steps)
  File "/disk/scratch/jiangming/workspace/DRTSparsing/OpenNMT-py/onmt/trainer.py", line 209, in train
    report_stats)
  File "/disk/scratch/jiangming/workspace/DRTSparsing/OpenNMT-py/onmt/trainer.py", line 318, in _gradient_accumulation
    outputs, attns = self.model(src, tgt, src_lengths, bptt=bptt)
  File "/disk/scratch/jiangming/workspace/DRTSparsing/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/disk/scratch/jiangming/workspace/DRTSparsing/OpenNMT-py/onmt/models/model.py", line 46, in forward
    memory_lengths=lengths)
  File "/disk/scratch/jiangming/workspace/DRTSparsing/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/disk/scratch/jiangming/workspace/DRTSparsing/OpenNMT-py/onmt/decoders/transformer.py", line 209, in forward
    step=step)
  File "/disk/scratch/jiangming/workspace/DRTSparsing/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/disk/scratch/jiangming/workspace/DRTSparsing/OpenNMT-py/onmt/decoders/transformer.py", line 75, in forward
    type="self")
  File "/disk/scratch/jiangming/workspace/DRTSparsing/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/disk/scratch/jiangming/workspace/DRTSparsing/OpenNMT-py/onmt/modules/multi_headed_attn.py", line 193, in forward
    scores = query_key + relative_matmul(query, relations_keys, True)
  File "/disk/scratch/jiangming/workspace/DRTSparsing/OpenNMT-py/onmt/utils/misc.py", line 116, in relative_matmul
    x_tz_matmul = torch.matmul(x_t_r, z_t)
RuntimeError: CUDA out of memory. Tried to allocate 614.62 MiB (GPU 1; 11.91 GiB total capacity; 10.02 GiB already allocated; 55.06 MiB free; 515.75 MiB cached)
```
The batch size is set to 8 and batch type is token. I think it is extremely small. Is there any optimization setting?

**Comment by michaelpradel** [comment]
I had the same problem, and it was due to some very long input sentences. I fixed it by removing/truncating those input sentences before passing the data to OpenNMT.
