### ISSUE TITLE
Image-to-Text CUDA out of memory during training (memory usage jumps)

### ISSUE THREAD

**Issue by wzlxjtu** [OpenNMT/OpenNMT-py#1376]
I'm training the image-to-text model with the im2latex-100K dataset. I'm using a GPU with 8 GB memory but my training runs out of memory even when batch_size=4. The [original paper](https://arxiv.org/pdf/1609.04938v1.pdf) stated that the GPU used has 12 GB memory, not much different from mine, but batch_size=20.

The parameters I gave: 
```python train.py -model_type img -data data_full/im2text/demo -save_model demo-model -gpu_ranks 0 -batch_size 4 -train_steps 500000 -max_grad_norm 20 -learning_rate 0.1 -word_vec_size 80 -encoder_type brnn -image_channel_size 1```

The error message I got after 700 seconds:
```
Traceback (most recent call last):
  File "/home/meca/OpenNMT-py/train.py", line 109, in <module>
    main(opt)
  File "/home/meca/OpenNMT-py/train.py", line 39, in main
    single_main(opt, 0)
  File "/home/meca/OpenNMT-py/onmt/train_single.py", line 116, in main
    valid_steps=opt.valid_steps)
  File "/home/meca/OpenNMT-py/onmt/trainer.py", line 209, in train
    report_stats)
  File "/home/meca/OpenNMT-py/onmt/trainer.py", line 318, in _gradient_accumulation
    outputs, attns = self.model(src, tgt, src_lengths, bptt=bptt)
  File "/home/meca/anaconda3/envs/v3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/meca/OpenNMT-py/onmt/models/model.py", line 42, in forward
    enc_state, memory_bank, lengths = self.encoder(src, lengths)
  File "/home/meca/anaconda3/envs/v3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/meca/OpenNMT-py/onmt/encoders/image_encoder.py", line 93, in forward
    src = F.relu(self.batch_norm1(self.layer3(src)), True)
  File "/home/meca/anaconda3/envs/v3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/meca/anaconda3/envs/v3/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 76, in forward
    exponential_average_factor, self.eps)
  File "/home/meca/anaconda3/envs/v3/lib/python3.6/site-packages/torch/nn/functional.py", line 1623, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 610.38 MiB (GPU 0; 7.93 GiB total capacity; 7.04 GiB already allocated; 143.88 MiB free; 37.81 MiB cached)
```

Before this happens, my memory usage looks like the following:
```                                                                              
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1553      G   /usr/lib/xorg/Xorg                            31MiB |
|    0      1581      G   /usr/bin/gnome-shell                          53MiB |
|    0      1896      G   /usr/lib/xorg/Xorg                           113MiB |
|    0      2024      G   /usr/bin/gnome-shell                         101MiB |
|    0      2484      G   /opt/teamviewer/tv_bin/TeamViewer             18MiB |
|    0      3124      G   /snap/pycharm-community/121/jre64/bin/java     2MiB |
|    0      5142      C   /home/meca/anaconda3/envs/v3/bin/python3    4251MiB |
+-----------------------------------------------------------------------------+
```

Seems like the memory all of a sudden jumps from 4G to 8G. Would you kindly help me find out why this happens? Doesn't seems reasonable to reduce the batch size further. Any methods to avoid this?

Thank you!

**Comment by vince62s** [comment]
is this happening at the very begining upfront ?

**Comment by wzlxjtu** [comment]
> is this happening at the very begining upfront ?

Around 1000 steps. Actually, I started doubting if it's the image size that's causing the issue. Maybe after some steps, it runs into an image batch with doubled size? Not sure if that's the cause but I will try to remove the larger images and try again.

**Comment by wzlxjtu** [comment]
Turns out that the image size is the issue. In the im2latex-100k dataset, some LaTex renders empty formulas, which couldn't be cropped by the preprocessing steps, thus ending in huge sizes. By removing these images, I got the training steps to work!
