### ISSUE TITLE
Always getting 'CUDA Out of Memory' Error

### ISSUE THREAD

**Issue by JustCunn** [OpenNMT/OpenNMT-py#1907]
I'm training a Transformer NMT model on 2 GPUs (on the same node). 

Here is my training config (note the train and dev files total about 200mb):
```
data:
    corpus1:
        path_src: fc_0507_upd/train.en
        path_tgt: fc_0507_upd/train.ga
    valid:
        path_src: fc_0507_upd/dev.en
        path_tgt: fc_0507_upd/dev.ga

save_model: checkpoints/onmt_2610_en-ga/model
src_vocab: fc_0507_upd/vocab.src
tgt_vocab: fc_0507_upd/vocab.tgt
save_checkpoint_steps: 5000
train_steps: 500000
valid_steps: 10000
warmup_steps: 8000
report_every: 100

encoder_type: transformer
decoder_type: transformer
word_vec_size: 512
rnn_size: 512
layers: 5
transformer_ff: 2048
heads: 8

optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0

batch_size: 32
dropout: 0.1
label_smoothing: 0.1

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

world_size: 2
gpu_ranks:
- 0
- 1
```
Just as training commences or a couple hundred steps in I get this error:
```
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/OpenNMT_py-2.0.0rc1-py3.7.egg/onmt/utils/distributed.py", line 209, in consumer
    batch_queue=batch_queue, semaphore=semaphore)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/OpenNMT_py-2.0.0rc1-py3.7.egg/onmt/train_single.py", line 107, in main
    valid_steps=opt.valid_steps)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/OpenNMT_py-2.0.0rc1-py3.7.egg/onmt/trainer.py", line 244, in train
    report_stats)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/OpenNMT_py-2.0.0rc1-py3.7.egg/onmt/trainer.py", line 368, in _gradient_accumulation
    with_align=self.with_align)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/OpenNMT_py-2.0.0rc1-py3.7.egg/onmt/models/model.py", line 51, in forward
    with_align=with_align)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/OpenNMT_py-2.0.0rc1-py3.7.egg/onmt/decoders/transformer.py", line 321, in forward
    with_align=with_align)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/OpenNMT_py-2.0.0rc1-py3.7.egg/onmt/decoders/transformer.py", line 93, in forward
    output, attns = self._forward(*args, **kwargs)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/OpenNMT_py-2.0.0rc1-py3.7.egg/onmt/decoders/transformer.py", line 157, in _forward
    attn_type="self")
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/OpenNMT_py-2.0.0rc1-py3.7.egg/onmt/modules/multi_headed_attn.py", line 203, in forward
    drop_attn = self.dropout(attn)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/torch/nn/modules/dropout.py", line 58, in forward
    return F.dropout(input, self.p, self.training, self.inplace)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/torch/nn/functional.py", line 973, in dropout
    else _VF.dropout(input, p, training))
RuntimeError: CUDA out of memory. Tried to allocate 356.00 MiB (GPU 0; 15.75 GiB total capacity; 14.29 GiB already allocated; 133.56 MiB free; 14.45 GiB reserved in total by PyTorch)
```

I've trained a model on OpenNMT-py before (albeit, the Legacy version with `onmt_preprocess`), and never gotten this OOM error before. The corpora are exactly the same too, just this time tokenized with Onmt not Subword-NMT/Moses. I haven't used V2.0 much, so perhaps there's something I'm overlooking here. 
I've tried lowering the batch size from 4096 to 32, lowering the amount of layers, lowering the transformer_ff size, but it all leads to OOM.

All advice welcome.

**Comment by francoishernandez** [comment]
VRAM usage should actually be a bit lower with 2.0
You might want to try the [`filtertoolong` transform](https://opennmt.net/OpenNMT-py/FAQ.html#filter-examples-by-length) to filter out long examples from your training data. (This was done at preprocessing before.)
You can add `transforms: ["filtertoolong"]` and change the value of the following opts if needed:
https://github.com/OpenNMT/OpenNMT-py/blob/6feb30905de59fbe98849f5c6f1f30b214c0f2a5/onmt/transforms/misc.py#L19-L22

(Note: these opts defaulted to 50 in the legacy version.)

> I've tried lowering the batch size from 4096 to 32

Careful, `batch_type` defaults to `sents`, so 4096 sents may be a bit much... Here it's probably better to put back 4096 and set `batch_type` to `tokens`.

**Comment by JustCunn** [comment]
Yes my bad, I just presumed that `filtertoolong` was applied automatically (like in `onmt_preprocessing`).  That did the trick and it's running now!

Thanks again
