### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by maheshmylavarapu0057** [OpenNMT/OpenNMT-py#2023]
I am trying to use this tool kit,I am running on corpus of size 32lakhes.
I tried-using a Batch size of 128,256.I got CUDA out of memory. My vocab size is 50k.Any suggestions will be appreciated.

**Comment by francoishernandez** [comment]
You might want to give more details:
- what is your task, what is your data like
- what version are you using
- what hardware are you using
- post your full config file(s) / command line(s)

**Comment by maheshmylavarapu0057** [comment]
Thank you for an early reply. But I fixed this problem. Please update the YAML file of transformers one.
It didn't have onmt_preprocess one. This step creates some .pt files, which splits the large corpus into some 2to 3 files and trains using data.pt files.

onmt_preprocess -train_src corpus.train.bpe.src -train_tgt corpus.train.bpe.tgt -valid_src corpus.dev.bpe.src -valid_tgt corpus.dev.bpe.tgt -save_data data -overwrite

**Comment by francoishernandez** [comment]
Not sure to understand the issue here. `onmt_preprocess` was removed in v2.
