### ISSUE TITLE
Getting ctypes.ArgumentError in train.py using CUDA 9

### ISSUE THREAD

**Issue by abaheti95** [OpenNMT/OpenNMT-py#421]
I was trying to test the code with the demo settings on my GPU and received this  ctypes.ArgumentError.  I am testing this on a linux GPU server with cuda-9.0.
```
~/OpenNMT-py$ python train.py -data data/demo -save_model demo-model -gpuid 0
Loading train and validate data from 'data/demo'
 * number of training sentences: 10000
 * maximum batch size: 64
 * vocabulary size. source = 24997; target = 35820
Building model...
Intializing model parameters.
Traceback (most recent call last):
  File "train.py", line 306, in <module>
    main()
  File "train.py", line 294, in main
    model = build_model(model_opt, opt, fields, checkpoint)
  File "train.py", line 232, in build_model
    use_gpu(opt), checkpoint)
  File "/home/baheti/OpenNMT-py/onmt/ModelConstructor.py", line 185, in make_base_model
    model.cuda()
  File "/home/baheti/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/baheti/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/baheti/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/baheti/.local/lib/python2.7/site-packages/torch/nn/modules/rnn.py", line 123, in _apply
    self.flatten_parameters()
  File "/home/baheti/.local/lib/python2.7/site-packages/torch/nn/modules/rnn.py", line 85, in flatten_parameters
    handle = cudnn.get_handle()
  File "/home/baheti/.local/lib/python2.7/site-packages/torch/backends/cudnn/__init__.py", line 296, in get_handle
    handle = CuDNNHandle()
  File "/home/baheti/.local/lib/python2.7/site-packages/torch/backends/cudnn/__init__.py", line 110, in __init__
    check_error(lib.cudnnCreate(ctypes.byref(ptr)))
  File "/home/baheti/.local/lib/python2.7/site-packages/torch/backends/cudnn/__init__.py", line 283, in check_error
    raise CuDNNError(status)
torch.backends.cudnn.CuDNNError: 4: CUDNN_STATUS_INTERNAL_ERROR
Exception ctypes.ArgumentError: "argument 1: <type 'exceptions.TypeError'>: Don't know how to convert parameter 1" in <bound method CuDNNHandle.__del__ of <torch.backends.cudnn.CuDNNHandle instance at 0x7f27e1b1c950>> ignored
```

I haven't changed a single line in the code and was expecting this to work. I also tried to check if torch is able to find the cudnn version and turns out it is able to find cuDNN!

```
>>> import torch
>>> torch.backends.cudnn.version()
7003
>>> print(torch.backends.cudnn.is_acceptable(torch.cuda.FloatTensor(1)))
True
```
Does anyone have any ideas for what did I do wrong here?

**Comment by abaheti95** [comment]
Hi all,

Turns out that GPU0 was not free and thus I was getting this allocation error. Sorry for spamming here with irrelevant question. Kindly delete this issue if possible.
